// <auto-generated />
using System;
using ASP_Webapp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASP_Webapp.Migrations
{
    [DbContext(typeof(CompanyContext))]
    [Migration("20220928193333_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.9");

            modelBuilder.Entity("ASP_Webapp.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("ASP_Webapp.Models.Employer", b =>
                {
                    b.Property<int>("EmployerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EmployerId");

                    b.ToTable("Employers");
                });

            modelBuilder.Entity("ASP_Webapp.Models.Salary", b =>
                {
                    b.Property<int>("SalaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EmployerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SalaryId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("EmployerId");

                    b.ToTable("Salaries");
                });

            modelBuilder.Entity("ASP_Webapp.Models.Salary", b =>
                {
                    b.HasOne("ASP_Webapp.Models.Employee", null)
                        .WithMany("Salaries")
                        .HasForeignKey("EmployeeId");

                    b.HasOne("ASP_Webapp.Models.Employer", null)
                        .WithMany("Salaries")
                        .HasForeignKey("EmployerId");
                });

            modelBuilder.Entity("ASP_Webapp.Models.Employee", b =>
                {
                    b.Navigation("Salaries");
                });

            modelBuilder.Entity("ASP_Webapp.Models.Employer", b =>
                {
                    b.Navigation("Salaries");
                });
#pragma warning restore 612, 618
        }
    }
}
